[package]
name = "xilem_abcdeez_mobile"
# Version is required by `cargo-apk`, though this value will never change.
version = "0.0.0"
edition = "2021"
description = "Example for building xilem on mobile and desktop"
publish = false
license = "MIT OR Apache-2.0"

[lib]
name = "xilem_abcdeez_mobile"
crate-type = ["staticlib", "cdylib", "lib"]

[dependencies]
abcdeez-app = { path = "../../xilem-app", features = ["embed-backend", "xilem-native"] }
winit.workspace = true
pollster = "0.3.0"

[package.metadata.android]
package = "online.fggoose.abcdeez"
apk_name = "xilemabcdeez"
# This strips debug symbols from the shared libraries, drastically reducing APK
# size. If you need them, remove the option.
strip = "strip"
build_targets = ["aarch64-linux-android", "armv7-linux-androideabi"]

[package.metadata.android.sdk]
min_sdk_version = 26
target_sdk_version = 35

[package.metadata.android.application]
label = "xilem abcdeez"
